[package]
name = "salesman"
version = "0.1.0"
edition = "2021"

# [profile.release]
# lto = true
# codegen-units = 1

[dependencies]
rand = "0.8.4"
plotters = "0.3.4"
ordered-float = "3.3.0"
permutations = "0.1.1"