[package]
name = "salesman"
version = "0.1.1"
edition = "2021"

[dependencies]
rand = "0.8.4"
rand_chacha = "0.3.1"
ordered-float = "3.3.0"
chrono = "0.4.22"
svg = "0.13.0"

[[bin]]
name = "chrono"
test = false
